# Generated by Django 4.1.3 on 2023-06-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoService", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("service", models.CharField(max_length=100)),
            ],
        ),
    ]
