# Generated by Django 4.1.3 on 2023-06-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoService", "0002_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
    ]
